dist: trusty
sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

matrix:
  include:
    - env: CABALVER="2.2" GHCVER="8.4.2"
      compiler: ": #GHC 8.4.2"
      addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.2], sources: [hvr-ghc]}}
    - os: osx
      env: CABALVER="2.2" GHCVER="8.4.2"
      compiler: ": #GHC 8.4.2"

    - env: CABALVER="2.2" GHCVER="8.2.2"
      compiler: ": #GHC 8.2.2"
      addons: {apt: {packages: [cabal-install-2.2,ghc-8.2.2], sources: [hvr-ghc]}}

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]];
    then
        brew update;
        brew install ghc;
        brew install cabal-install;
    fi
  - unset CC
  - export PATH=/opt/ghc/bin:$HOME/.cabal/bin:$PATH

script:
  - cabal update
  - cabal new-build -j --disable-optimization --allow-newer
